const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../web');
function worker(){const handlers={},cacheOps=[],cache={addAll:async files=>{cacheOps.push(files)},match:async url=>'cached:'+url};let activated=0;
const self={registration:{scope:'https://example.org/gi/'},location:{origin:'https://example.org'},clients:{claim:async()=>{}},skipWaiting:()=>{activated++},addEventListener:(name,fn)=>handlers[name]=fn};
const caches={open:async()=>cache,keys:async()=>['gi-resident-content-old','other-app'],delete:async k=>cacheOps.push(k)};
const src=fs.readFileSync(path.join(root,'sw-template.txt'),'utf8').replace('__VERSION__','1.0.0').replace('__FILES__',JSON.stringify(['./','./app.js','./index.html']));
vm.runInNewContext(src,{self,caches,URL,Request,fetch:async r=>'network'});return {handlers,cacheOps,get activated(){return activated}}}
test('manifest supports standalone mobile installation and valid icon sizes',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest')));assert.equal(m.display,'standalone');assert.equal(m.scope,'./');for(const icon of m.icons){const b=fs.readFileSync(path.join(root,icon.src));assert.equal(b.subarray(1,4).toString(),'PNG');assert.equal(b.readUInt32BE(16),parseInt(icon.sizes))}});
test('API responses and cross-origin requests bypass caching',()=>{const w=worker();for(const url of ['https://example.org/api/profile','https://example.org/gi/api/login','https://other.org/app.js']){let intercepted=false;w.handlers.fetch({request:{url,method:'GET'},respondWith:()=>intercepted=true});assert.equal(intercepted,false)}});
test('POST and unlisted files bypass caching',()=>{const w=worker();for(const [url,method]of [['https://example.org/gi/app.js','POST'],['https://example.org/gi/private/user.json','GET']]){let used=false;w.handlers.fetch({request:{url,method},respondWith:()=>used=true});assert.equal(used,false)}});
test('versioned query strings resolve to cached static resource',async()=>{const w=worker();let response;w.handlers.fetch({request:{url:'https://example.org/gi/app.js?v=old',method:'GET'},respondWith:p=>response=p});assert.equal(await response,'cached:https://example.org/gi/app.js')});
test('installation waits for full cache and does not force activation',async()=>{const w=worker();let task;w.handlers.install({waitUntil:p=>task=p});await task;assert.equal(w.cacheOps.flat().length,3);assert.equal(w.activated,0);w.handlers.message({data:{type:'ACTIVATE_RELEASE'}});assert.equal(w.activated,1)});
test('activation removes only own older caches',async()=>{const w=worker();let task;w.handlers.activate({waitUntil:p=>task=p});await task;assert.deepEqual(w.cacheOps,['gi-resident-content-old'])});
