
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const BASE_PROFILES=[];
const KEY='giV24-learning';
let db;try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){window.GI24_STORAGE_ERROR='本地记录无法解析；原记录未删除，请先备份浏览器数据。'}db=db||{profiles:{},customCases:[],teacherNote:'',settings:{}};
BASE_PROFILES.forEach(n=>db.profiles[n]=db.profiles[n]||{scores:{},wrong:[],img:{ok:0,total:0},xp:0,streak:1,last:null,history:[]});
function ensureProfile(p){if(!p)return p;p.scores=p.scores||{};p.wrong=p.wrong||[];p.img=p.img||{ok:0,total:0};p.history=p.history||[];p.xp=p.xp||0;p.anatomy=p.anatomy||{ok:0,total:0,best:0};p.procedures=p.procedures||{};return p}
Object.values(db.profiles).forEach(ensureProfile);
let session=null;
let currentCase=null, ordered={}, chatHistory=[], phase=0, freeScores={dx:0,diff:0,plan:0}, aiAvailable=false;
function save(){try{if(!window.GI24_REMOTE) localStorage.setItem(KEY,JSON.stringify(db));if(window.queueProfileSync)queueProfileSync()}catch(e){window.GI24_STORAGE_ERROR='保存失败：请立即导出学习备份。';if(window.showSaveError)showSaveError()}}
function persistSession(){if(!window.GI24_REMOTE)sessionStorage.setItem('gi24Session',JSON.stringify(session))}
function allCases(){return [...GI_CASES,...db.customCases]}
function prof(){return session&&session.role==='resident'?ensureProfile(db.profiles[session.name]):null}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s=''){return String(s).normalize('NFKC').toLowerCase().replace(/\s+/g,'')}
function login(){if(window.renderAccountLogin)renderAccountLogin()}
function app(){document.body.innerHTML=`<div class="shell"><aside class="side"><div class="logo">GI Resident AI<small>RESIDENCY TRAINING · V19</small></div><div class="profile"><b>${esc(session.name)}</b><span>${session.role==='teacher'?'管理员端':'住培学习档案'}</span></div><div class="nav" id="nav"></div></aside><main class="main" id="main"></main></div><div class="modal" id="modal"><button onclick="closeModal()">×</button><img id="modalImg"></div>`;buildNav();nav(session.role==='teacher'?'teacher':'dashboard')}
function buildNav(){let items=session.role==='teacher'?[['teacher','📊 管理员总览'],['caseadmin','🧩 病例管理'],['refs','📚 指南/图片来源'],['logout','↩ 退出']]:[['dashboard','🏠 今日学习'],['cases','🏥 AI虚拟病房'],['anatomy','🧭 镜下解剖地图'],['procedures','🎮 内镜操作训练营'],['images','🔬 真实内镜闯关'],['wrong','📝 错题本'],['report','📈 能力报告'],['refs','📚 指南/图片来源'],['logout','↩ 退出']];$('#nav').innerHTML=items.map(x=>`<button data-v="${x[0]}">${x[1]}</button>`).join('');$$('#nav button').forEach(b=>b.onclick=()=>b.dataset.v==='logout'?logout():nav(b.dataset.v))}
function logout(){sessionStorage.removeItem('gi24Session');session=null;login()}
function nav(v){$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));({dashboard,cases,anatomy,procedures,images,wrong,report,refs,teacher,caseadmin}[v]||dashboard)()}
function head(t,s,b=''){return `<div class="top"><div><h1>${esc(t)}</h1><p>${esc(s||'')}</p></div>${b?`<span class="pill">${esc(b)}</span>`:''}</div>`}
function metric(k,v,s=''){return `<div class="card metric"><span>${esc(k)}</span><strong>${esc(v)}</strong><span>${esc(s)}</span></div>`}
function dailyCase(){let a=allCases();return a[Math.floor((new Date().setHours(0,0,0,0)/86400000)%a.length)]}
function dashboard(){let p=prof(),done=Object.keys(p.scores).length,avg=done?Math.round(Object.values(p.scores).reduce((a,b)=>a+b,0)/done):0,d=dailyCase();$('#main').innerHTML=head('今日学习',`${esc(session.name)}，今天继续把“临床工作”变成可重复训练。`,'本地数据')+`<div class="grid g4">${metric('完成病例',done,`/ ${allCases().length}`)}${metric('最近病例决策均分',avg+'%','不含文字覆盖分')}${metric('内镜正确率',p.img.total?Math.round(p.img.ok/p.img.total*100)+'%':'0%',`${p.img.ok}/${p.img.total}`)}${metric('学习积分',p.xp,'XP')}</div><div class="section"><h2>🎯 今日病例</h2><small>每日自动轮换</small></div><div class="card"><div class="tags"><span class="tag ${d.level==='非典型'?'atyp':''}">${d.level}</span><span class="tag">${d.system}</span><span class="tag hard">${d.difficulty}</span></div><h2>${d.title}</h2><p style="color:#667085">${d.age}岁${d.sex}性 · ${d.chief}</p><button class="btn" onclick="startCase('${d.id}')">进入病例推理</button></div><div class="section"><h2>内镜技能小游戏</h2><small>5–10分钟完成一轮</small></div><div class="grid g2"><div class="card game-hero anatomy-hero"><span class="pill">NEW · Anatomy</span><h2>🧭 镜下解剖地图</h2><p>沿胃镜/肠镜真实路线认识食管、胃、十二指肠、结肠和回肠末端；再做部位识别闯关。</p><button class="btn" onclick="nav('anatomy')">开始认部位</button></div><div class="card game-hero procedure-hero"><span class="pill">NEW · Procedure Lab</span><h2>🎮 内镜操作训练营</h2><p>ESD、EMR、POEM、APC、ERCP、EUS-FNA/FNB、ERAT等：步骤排序 + 器械选择 + 风险决策。</p><button class="btn" onclick="nav('procedures')">进入训练营</button></div></div><div class="section"><h2>推荐训练</h2><small>优先补未完成与低分病例</small></div><div class="casegrid">${recommendCases(p).slice(0,6).map(caseCard).join('')}</div>`;bindCases()}
function recommendCases(p){return allCases().slice().sort((a,b)=>((p.scores[a.id]??-1)-(p.scores[b.id]??-1)))}
function caseCard(c){let p=prof(),sc=p?.scores?.[c.id];return `<div class="case" data-id="${c.id}"><div class="tags"><span class="tag ${c.level==='非典型'?'atyp':''}">${c.level}</span><span class="tag">${c.system}</span><span class="tag hard">${c.difficulty}</span></div><h3>${c.title}</h3><p>${c.age}岁${c.sex}性 · ${c.chief}</p>${sc!=null?`<div style="margin-top:10px" class="bar"><i style="width:${sc}%"></i></div><p style="margin-top:5px">历史最好 ${sc}%</p>`:''}</div>`}
function bindCases(){$$('.case').forEach(x=>x.onclick=()=>startCase(x.dataset.id))}
function cases(){let systems=[...new Set(allCases().map(c=>c.system))];$('#main').innerHTML=head('AI虚拟病房','32个典型与非典型病例。先问诊、开检查，再形成诊断和处置。',`${allCases().length} cases`)+`<div class="toolbar"><input id="q" placeholder="搜索疾病/症状"><select id="sys"><option value="">全部系统</option>${systems.map(s=>`<option>${s}</option>`).join('')}</select><select id="lev"><option value="">全部类型</option><option>典型</option><option>非典型</option></select><select id="dif"><option value="">全部难度</option><option>入门</option><option>进阶</option></select></div><div class="casegrid" id="cg">${allCases().map(caseCard).join('')}</div>`;bindCases();let f=()=>{let q=norm($('#q').value),s=$('#sys').value,l=$('#lev').value,d=$('#dif').value;$$('.case').forEach(el=>{let c=allCases().find(x=>x.id===el.dataset.id),ok=(!q||norm(c.title+c.chief+c.system).includes(q))&&(!s||c.system===s)&&(!l||c.level===l)&&(!d||c.difficulty===d);el.style.display=ok?'block':'none'})};$('#q').oninput=f;$('#sys').onchange=f;$('#lev').onchange=f;$('#dif').onchange=f}
function startCase(id){currentCase=allCases().find(c=>c.id===id);ordered={};chatHistory=[{who:'ai',text:'你是今天的一线住院医师。先从病史开始：你可以自由输入问题，例如“有没有黑便？”“最近用过什么药？”；也可以直接开检查。'}];phase=0;freeScores={dx:0,diff:0,plan:0};if(window.beginCase24)beginCase24(currentCase);renderWard()}
function renderWard(){if(window.captureCaseDraft24)captureCaseDraft24();let c=currentCase,img=window.GI24_MODE==='selftest'&&!Object.keys(ordered).some(k=>/内镜|胃镜|结肠镜|EUS|ERCP|病理/.test(k))?null:c.imageMeta;$('#main').innerHTML=head(window.caseTitle24?caseTitle24(c):c.title,`${c.level} · ${c.system} · ${c.difficulty}`,'病例推理')+`<div class="stage"><span class="${phase===0?'on':''}">1 接诊问诊</span><span class="${phase===1?'on':''}">2 开检查</span><span class="${phase===2?'on':''}">3 诊断/鉴别</span><span class="${phase===3?'on':''}">4 处置决策</span><span class="${phase===4?'on':''}">5 上级点评</span></div><div class="ward"><div class="card"><div class="patient-head"><div><b>${c.age}岁 ${c.sex}性</b><div style="color:#667085;margin-top:4px">主诉：${c.chief}</div></div><span class="pill">患者</span></div><div class="vitals">${c.vitals}</div><p>${c.intro}</p>${img?`<div class="imgbox"><img src="${img.src}" alt="教学图像" onclick="openModal(this.src)" referrerpolicy="no-referrer"></div><div class="src">真实医学图片：${img.credit} · ${window.GI24_MODE==='selftest'?'来源可在学习模式及资料页查看':`<a href="${img.source}" target="_blank">原始页面/授权</a>`}</div>`:''}<div class="section" style="margin-top:16px"><h2>自由问诊</h2><span id="aiState" class="ai-status">本地规则问答</span></div><div class="chat" id="chat">${chatHistory.map(m=>`<div class="msg ${m.who}">${esc(m.text)}</div>`).join('')}</div><div class="composer"><input id="ask" placeholder="例如：有没有黑便？最近吃过什么药？"><button class="btn" id="send">询问</button></div><div class="orders">${['血常规','肝肾功能','凝血','血型交叉','感染/炎症','腹部超声','增强CT','CTA','胃镜','结肠镜','MRCP','EUS','病理'].map(x=>`<button class="order" data-o="${x}">+ ${x}</button>`).join('')}</div></div><div class="card"><div class="section" style="margin-top:0"><h2>检查结果</h2><small>只显示主动选择的检查</small></div><div class="results" id="results">${renderResults()}</div><div class="section"><h2>形成临床判断</h2><small>规则核对核心表达；临床完整性由教师复核</small></div><div class="freebox"><label><b>最可能诊断</b></label><textarea id="dx" placeholder="写出你的诊断"></textarea><button class="btn soft" data-score="dx">提交诊断</button><div id="fdx"></div><br><label><b>主要鉴别诊断</b></label><textarea id="diff" placeholder="至少写2个鉴别"></textarea><button class="btn soft" data-score="diff">提交鉴别</button><div id="fdiff"></div><br><label><b>下一步处置计划</b></label><textarea id="plan" placeholder="写复苏、检查、药物、内镜/介入/手术等计划"></textarea><button class="btn soft" data-score="plan">提交计划</button><div id="fplan"></div></div><button class="btn" id="decision" style="margin-top:14px">进入关键决策题 →</button><button class="btn ghost" onclick="nav('cases')" style="margin-top:14px">退出病例</button></div></div>`;
setTimeout(()=>{let ch=$('#chat');ch.scrollTop=ch.scrollHeight},0);$('#send').onclick=askPatient;$('#ask').onkeydown=e=>{if(e.key==='Enter')askPatient()};$$('.order').forEach(b=>b.onclick=()=>orderTest(b.dataset.o));$$('[data-score]').forEach(b=>b.onclick=()=>scoreFree(b.dataset.score));$('#decision').onclick=()=>{phase=3;renderDecision(0,0)};checkAI();if(window.restoreCaseDraft24)restoreCaseDraft24()}
function renderResults(){let keys=Object.keys(ordered);return keys.length?keys.map(k=>`<div class="result"><b>${esc(k)}</b><br>${esc(ordered[k])}</div>`).join(''):'<div class="result">尚未开任何检查。先根据病史决定检查，不要“一键全套”。</div>'}
function localPatientAnswer(q){let nq=norm(q),best=null,bestN=0;for(let item of currentCase.qa){let n=item.keys.filter(k=>nq.includes(norm(k))).length;if(n>bestN){best=item;bestN=n}}if(best)return best.answer;if(nq.includes('为什么')||nq.includes('怎么办'))return '这是需要你作为医生判断的问题，我只能回答我的症状和既往情况。';return '这个方面我没有特别印象。你可以换一种更具体的问法，或继续询问用药、既往史、伴随症状和危险因素。'}
async function askPatient(){let input=$('#ask'),q=input.value.trim();if(!q)return;chatHistory.push({who:'user',text:q});input.value='';let ans=localPatientAnswer(q);if(aiAvailable){try{let r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'patient',case:currentCase,history:chatHistory,message:q})});if(r.ok){let j=await r.json();if(j.text)ans=j.text}else aiAvailable=false}catch(e){aiAvailable=false}}chatHistory.push({who:'patient',text:ans});phase=Math.max(phase,0);renderWard()}
function mapOrder(name){let t=currentCase.tests||{},entries=Object.entries(t);let aliases={
'血常规':['血常规'],'肝肾功能':['肝肾','肝功能','肾功能','电解质'],'凝血':['凝血'],'血型交叉':['血型','交叉'],'感染/炎症':['CRP','感染','血培养','粪便','WBC'],'腹部超声':['超声'],'增强CT':['增强CT','CT','胰腺协议'],'CTA':['CTA'],'胃镜':['胃镜','白光胃镜','NBI'],'结肠镜':['结肠镜'],'MRCP':['MRCP'],'EUS':['EUS'],'病理':['病理','活检','刷检']};
let ks=aliases[name]||[name];let hit=entries.filter(([k])=>ks.some(a=>norm(k).includes(norm(a))));return hit}
function orderTest(name){let hits=mapOrder(name);if(!hits.length){ordered[name]='本病例数据库中没有预设该检查的特异结果；临床上请根据指征选择，避免机械式全套检查。'}else hits.forEach(([k,v])=>ordered[k]=v);phase=Math.max(phase,1);renderWard()}
function matchScore(text,targets){let n=norm(text),hit=targets.filter(t=>{let parts=t.split(/[、/（）()，,\s]+/).filter(x=>x.length>=2);return parts.some(p=>n.includes(norm(p))) });return {hit,total:targets.length,score:targets.length?Math.round(hit.length/targets.length*100):0}}
function scoreFree(type){let text=$('#'+type).value.trim();if(!text)return alert('请先写出你的判断');let ts=currentCase.targets[type==='dx'?'diagnosis':type==='diff'?'differential':'plan'];let r=matchScore(text,ts);freeScores[type]=r.score;phase=Math.max(phase,2);let el=$('#f'+type),label=type==='dx'?'诊断':type==='diff'?'鉴别':'计划';let missing=ts.filter(x=>!r.hit.includes(x));el.className='feedback '+(r.score>=60?'good':'mid');el.innerHTML=`<b>${label}匹配度 ${r.score}%</b><br>${r.score>=60?'核心方向基本抓住。':'思路还不完整。'}${missing.length?`<br>上级医师追问：你是否还需要考虑/补充——${missing.slice(0,3).join('、')}？`:''}`}
function renderDecision(i,correct){let c=currentCase,d=c.decisions[i];$('#main').innerHTML=head('关键决策',c.title,`${i+1}/${c.decisions.length}`)+`<div class="card" style="max-width:850px;margin:auto"><h2>${d.q}</h2><div class="choices">${d.o.map((o,j)=>`<div class="choice" data-i="${j}">${String.fromCharCode(65+j)}. ${o}</div>`).join('')}</div><div id="exp"></div><div class="row" style="justify-content:space-between;margin-top:16px"><button class="btn ghost" onclick="renderWard()">返回病房</button><button class="btn hidden" id="next">${i===c.decisions.length-1?'查看上级医师总评':'下一题'}</button></div></div>`;let locked=false;$$('.choice').forEach(x=>x.onclick=()=>{if(locked)return;locked=true;let pick=+x.dataset.i,ok=pick===d.a;$$('.choice').forEach(y=>{let j=+y.dataset.i;if(j===d.a)y.classList.add('correct');if(j===pick&&!ok)y.classList.add('wrong')});if(!ok)addWrong(c,d,pick);$('#exp').className='feedback '+(ok?'good':'mid');$('#exp').innerHTML=`<b>${ok?'✓ 正确':'✗ 需要修正'}</b><br>${d.why}`;let n=$('#next');n.classList.remove('hidden');n.onclick=()=>i<c.decisions.length-1?renderDecision(i+1,correct+(ok?1:0)):finishCase(correct+(ok?1:0))})}
function addWrong(c,d,pick){let p=prof();p.wrong.unshift({caseId:c.id,caseTitle:c.title,q:d.q,picked:d.o[pick],right:d.o[d.a],why:d.why,at:new Date().toISOString()});save()}
function finishCase(correct){phase=4;let c=currentCase,p=prof(),decisionPct=Math.round(correct/c.decisions.length*100),freeAvg=Math.round((freeScores.dx+freeScores.diff+freeScores.plan)/3),score=Math.round(decisionPct*.65+freeAvg*.35);let prev=p.scores[c.id]||0;p.scores[c.id]=score;p.xp+=20+correct*5;p.history.unshift({caseId:c.id,title:c.title,score,at:new Date().toISOString()});save();let weakest=Object.entries(freeScores).sort((a,b)=>a[1]-b[1])[0][0],weakLabel={dx:'诊断表达',diff:'鉴别诊断',plan:'处置计划'}[weakest];$('#main').innerHTML=head('AI上级医师总评',c.title,'病例完成')+`<div class="grid g3">${metric('综合成绩',score+'%','自由文本35% + 决策65%')}${metric('关键决策',decisionPct+'%',`${correct}/${c.decisions.length}`)}${metric('最需加强',weakLabel,'本例反馈')}</div><div class="card" style="margin-top:16px"><h2>上级医师点评</h2><p>${score>=80?'你的临床优先级和关键决策总体可靠。下一轮尝试更精炼地表达“为什么”，并主动提出升级治疗触发条件。':score>=60?'基本方向正确，但仍存在关键步骤遗漏。建议重做错题，并在自由文本中把鉴别和处置写得更结构化。':'当前更像“知道病名但流程不够完整”。建议重新从问诊开始，减少一键开检查，明确每一步检查和治疗的目的。'}</p><h3>本病例必须带走的3个点</h3><ul>${c.pearls.map(x=>`<li>${x}</li>`).join('')}</ul><div class="row"><button class="btn" onclick="startCase('${c.id}')">再练一次</button><button class="btn soft" onclick="nav('wrong')">查看错题</button><button class="btn ghost" onclick="nav('cases')">返回病例库</button></div></div>`}
async function checkAI(){aiAvailable=false;if(location.protocol==='file:')return;try{let r=await fetch('/api/health');if(r.ok){let j=await r.json();aiAvailable=!!j.ai;if(aiAvailable){$('#aiState').textContent='联网AI模式';$('#aiState').classList.add('on')}}}catch(e){aiAvailable=false}}
let iq=0;function images(){iq=0;imageQ()}
function imageQ(){let x=GI_IMAGE_QUIZ[iq],im=GI_IMAGES[x.img];$('#main').innerHTML=head('真实内镜图像闯关','先判断，作答后才显示答案与解释。所有图片均链接至真实开放医学图片源。',`${iq+1}/${GI_IMAGE_QUIZ.length}`)+`<div class="ward"><div class="card"><div class="imgbox"><img src="${im.src}" onclick="openModal(this.src)" referrerpolicy="no-referrer"></div><div class="src">${im.credit} · <a target="_blank" href="${im.source}">原图/授权</a></div></div><div class="card"><h2>${x.q}</h2><div class="choices">${x.o.map((o,i)=>`<div class="choice" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</div>`).join('')}</div><div id="iexp"></div><button class="btn hidden" id="inext" style="margin-top:14px">${iq===GI_IMAGE_QUIZ.length-1?'完成':'下一张'}</button></div></div>`;let locked=false;$$('.choice').forEach(el=>el.onclick=()=>{if(locked)return;locked=true;let i=+el.dataset.i,ok=i===x.a,p=prof();if(window.moduleResponse24)moduleResponse24(x.q,x.o,i,ok,x.a,x.why);p.img.total++;if(ok)p.img.ok++;if(!ok)p.wrong.unshift({caseId:'IMAGE',caseTitle:x.title,q:x.q,picked:x.o[i],right:x.o[x.a],why:x.why,at:new Date().toISOString()});save();$$('.choice').forEach(y=>{let j=+y.dataset.i;if(j===x.a)y.classList.add('correct');if(j===i&&!ok)y.classList.add('wrong')});$('#iexp').className='feedback '+(ok?'good':'mid');$('#iexp').innerHTML=`<b>${ok?'✓ 正确':'✗ 错误'}</b><br>${x.why}`;$('#inext').classList.remove('hidden');$('#inext').onclick=()=>{if(iq<GI_IMAGE_QUIZ.length-1){iq++;imageQ()}else {if(window.finishModule24){let a=GI24_ACTIVE();finishModule24('images','内镜图像练习',Math.round(a.responses.filter(x=>x.correct).length/a.responses.length*100))}report()}}})}
function wrong(){let p=prof();$('#main').innerHTML=head('错题本','保存最近100条错误决策与图像题，复习后可删除。',`${p.wrong.length} 条`)+`<div class="card">${p.wrong.length?p.wrong.map((w,i)=>`<div class="wrongitem"><b>${esc(w.caseTitle)}</b><br>${esc(w.q)}<br><span style="color:#b42318">你的选择：${esc(w.picked)}</span><br><span style="color:#067647">正确：${esc(w.right)}</span><br><span class="mini">${esc(w.why)}</span><br><button class="btn bad" style="margin-top:6px;padding:5px 8px" onclick="removeWrong(${i})">已掌握，移除</button></div>`).join(''):'<div style="padding:40px;text-align:center;color:#667085">暂无错题 🎉</div>'}</div>`}
function removeWrong(i){prof().wrong.splice(i,1);save();wrong()}
function report(){let p=prof(),groups={};allCases().forEach(c=>{groups[c.system]=groups[c.system]||[];if(p.scores[c.id]!=null)groups[c.system].push(p.scores[c.id])});let rows=Object.entries(groups).map(([k,a])=>[k,a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0,a.length]).sort((a,b)=>b[1]-a[1]);$('#main').innerHTML=head('能力报告','自动按系统汇总已完成病例，并保留最近训练历史。')+`<div class="grid g3">${metric('完成病例',Object.keys(p.scores).length,`/ ${allCases().length}`)}${metric('图像正确率',p.img.total?Math.round(p.img.ok/p.img.total*100)+'%':'0%',`${p.img.ok}/${p.img.total}`)}${metric('待复习错题',p.wrong.length,'错题本')}${metric('解剖闯关',p.anatomy.total?Math.round(p.anatomy.ok/p.anatomy.total*100)+'%':'0%',`${p.anatomy.ok}/${p.anatomy.total}`)}${metric('操作训练',Object.keys(p.procedures).length,'已练术式')}</div><div class="section"><h2>分系统掌握度</h2></div><div class="card">${rows.map(r=>`<div style="display:grid;grid-template-columns:150px 1fr 60px;gap:10px;align-items:center;margin:12px 0"><b>${r[0]}</b><div class="bar"><i style="width:${r[1]}%"></i></div><span>${r[2]?r[1]+'%':'未练'}</span></div>`).join('')}</div><div class="section"><h2>最近训练</h2></div><div class="card"><table class="table"><tr><th>病例</th><th>成绩</th><th>时间</th></tr>${p.history.slice(0,12).map(h=>`<tr><td>${esc(h.title)}</td><td>${h.score}%</td><td>${new Date(h.at).toLocaleString()}</td></tr>`).join('')}</table></div>`}
function refs(){let im=Object.values(GI_IMAGES);$('#main').innerHTML=head('指南与真实图片来源','教学内容为住培训练用；正式院内部署前建议由专科教师逐条审校。')+`<div class="card"><h2>临床参考</h2>${GI_REFS.map(r=>`<div class="ref"><b>${r.title}</b><br><span class="mini">${r.note}</span><br><a href="${r.url}" target="_blank">${r.url}</a></div>`).join('')}</div><div class="section"><h2>内镜操作培训参考</h2></div><div class="card">${(window.GI_PROCEDURE_REFS||[]).map(r=>`<div class="ref"><b>${r.title}</b><br><a href="${r.url}" target="_blank">${r.url}</a></div>`).join('')}</div><div class="section"><h2>图像来源</h2><small>点击原图页面核验作者与许可证</small></div><div class="card">${im.map(r=>`<div class="ref"><span class="mini">${r.credit}</span><br><a href="${r.source}" target="_blank">${r.source}</a></div>`).join('')}</div><div class="notice" style="margin-top:14px">Wikimedia Commons不同文件采用不同许可证。内部教学原型可链接展示；如需把图片打包进医院正式产品、公开网站、论文或商业软件，请逐张核验并履行署名/相同方式共享等要求。</div>`}
function teacher(){let names=Object.keys(db.profiles);let data=names.map(n=>{let p=db.profiles[n],vals=Object.values(p.scores);return [n,vals.length,vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0,p.img.total?Math.round(p.img.ok/p.img.total*100):0,p.wrong.length,p.xp]});$('#main').innerHTML=head('教师总览','本地演示版：同一浏览器中的学员档案会汇总到这里。','Teacher')+`<div class="grid g4">${metric('学员数',names.length)}${metric('内置病例',GI_CASES.length)}${metric('自建病例',db.customCases.length)}${metric('总训练次数',names.reduce((s,n)=>s+db.profiles[n].history.length,0))}</div><div class="section"><h2>学员表现</h2></div><div class="card"><table class="table"><tr><th>学员</th><th>完成病例</th><th>平均分</th><th>图像正确率</th><th>错题</th><th>XP</th></tr>${data.map(r=>`<tr>${r.map((x,i)=>`<td>${i===0?esc(x):x+(i===2||i===3?'%':'')}</td>`).join('')}</tr>`).join('')}</table></div><div class="section"><h2>数据备份</h2></div><div class="card row"><button class="btn" onclick="exportData()">导出全部学习数据 JSON</button><label class="btn ghost">导入数据<input type="file" id="importFile" accept="application/json" style="display:none"></label><button class="btn bad" onclick="resetAll()">清空全部本地数据</button></div>`;$('#importFile').onchange=importData}
function exportData(){let blob=new Blob([JSON.stringify({format:'gi24-learning-backup',version:GI24.VERSION,profiles:db.profiles},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='GI_Resident_AI_V24_learning_backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();teacher();alert('导入成功')}catch(e){alert('JSON格式错误')}};r.readAsText(f)}
function resetAll(){if(confirm('确定清空全部学习数据？该操作不可撤销。')){localStorage.removeItem(KEY);location.reload()}}
function caseadmin(){$('#main').innerHTML=head('病例管理','教师可新增本院自定义训练病例；本地版先支持基础字段，正式服务器版可扩展多人协作。')+`<div class="grid g2"><div class="card teach-form"><h2>新增自定义病例</h2><input id="ct" placeholder="病例标题"><select id="cs"><option>消化道出血</option><option>食管</option><option>胃</option><option>IBD/肠道</option><option>胰胆</option><option>肝病</option></select><input id="ca" type="number" value="50" placeholder="年龄"><select id="csex"><option>男</option><option>女</option></select><input id="cc" placeholder="主诉"><textarea id="ci" placeholder="病例导语/病史摘要"></textarea><input id="cdx" placeholder="标准诊断"><button class="btn" id="addc">保存自定义病例</button></div><div class="card"><h2>病例库</h2><p>内置 ${GI_CASES.length} 例 · 自建 ${db.customCases.length} 例</p><div style="max-height:520px;overflow:auto">${allCases().map(c=>`<div class="ref"><b>${esc(c.title)}</b><br><span class="mini">${c.system} · ${c.level} · ${c.difficulty}${c.custom?' · 自建':''}</span>${c.custom?`<br><button class="btn bad" style="padding:5px 8px;margin-top:5px" onclick="delCustom('${c.id}')">删除</button>`:''}</div>`).join('')}</div></div></div>`;$('#addc').onclick=()=>{let title=$('#ct').value.trim(),dx=$('#cdx').value.trim();if(!title||!dx)return alert('至少填写病例标题和标准诊断');let id='CUSTOM-'+Date.now();db.customCases.push({id,title,system:$('#cs').value,level:'自建',difficulty:'进阶',age:+$('#ca').value,sex:$('#csex').value,chief:$('#cc').value||'待补充',vitals:'教师自建病例：生命体征待补充',intro:$('#ci').value||'教师自建病例。',qa:[{keys:['症状'],answer:'请由教师继续补充本病例问诊规则。'}],tests:{'基础检查':'请由教师在正式服务器版补充检查结果。'},targets:{diagnosis:[dx],differential:['鉴别诊断'],plan:['进一步检查','治疗计划']},pearls:['这是教师自建病例，请在后续正式后台完善教学要点。'],decisions:[{q:'最可能诊断？',o:[dx,'需要进一步鉴别','无法判断'],a:0,why:'教师预设标准诊断。'}],custom:true});save();caseadmin();alert('已添加')}}
function delCustom(id){if(confirm('删除该自建病例？')){db.customCases=db.customCases.filter(c=>c.id!==id);save();caseadmin()}}
function openModal(src){$('#modalImg').src=src;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}


// ===== v3.5 Endoscopy Anatomy & Procedure Games =====
let anatomyMode='upper', anatomyIndex=0, anatomyQuizIndex=0, anatomyQuizScore=0;
function anatomy(){anatomyMode='upper';anatomyIndex=0;renderAnatomyHub()}
function renderAnatomyHub(){let A=GI_ANATOMY[anatomyMode],p=prof();$('#main').innerHTML=head('镜下解剖地图','不是背解剖名词，而是把“镜身位置—内镜画面—临床操作”连起来。','Endoscopy Anatomy')+`<div class="anatomy-tabs"><button class="${anatomyMode==='upper'?'active':''}" onclick="switchAnatomy('upper')">⬇ 上消化道路线</button><button class="${anatomyMode==='lower'?'active':''}" onclick="switchAnatomy('lower')">⬆ 下消化道路线</button><button onclick="startAnatomyQuiz()">🎯 随机部位闯关</button></div><div class="grid g2"><div class="card"><h2>${A.title}</h2><p class="muted">${A.subtitle}</p><div class="scope-route">${A.nodes.map((n,i)=>`<button class="route-node ${i===anatomyIndex?'active':''}" onclick="showAnatomyNode(${i})"><span>${String(i+1).padStart(2,'0')}</span>${n.short}</button>`).join('')}</div><div class="route-tip">💡 <b>训练方法：</b>先按镜子前进顺序点击部位；熟悉后点击“随机部位闯关”，仅凭内镜线索判断位置。</div></div><div id="anatomyDetail"></div></div><div class="section"><h2>镜下定位速记</h2><small>用“结构标志”而不是凭感觉</small></div><div class="anatomy-summary">${A.nodes.map((n,i)=>`<div class="landmark-card" onclick="showAnatomyNode(${i})"><b>${n.name}</b><span>${n.landmark}</span></div>`).join('')}</div>`;renderAnatomyDetail()}
function switchAnatomy(m){anatomyMode=m;anatomyIndex=0;renderAnatomyHub()}
function showAnatomyNode(i){anatomyIndex=i;renderAnatomyHub()}
function renderAnatomyDetail(){let n=GI_ANATOMY[anatomyMode].nodes[anatomyIndex],im=GI_IMAGES[n.img];let box=$('#anatomyDetail');if(!box)return;box.innerHTML=`<div class="card anatomy-detail"><div class="route-kicker">${anatomyMode==='upper'?'UPPER GI':'LOWER GI'} · ${anatomyIndex+1}/${GI_ANATOMY[anatomyMode].nodes.length}</div><h2>${n.name}</h2><div class="anatomy-fact"><span>镜身路线</span><b>${n.route}</b></div><div class="anatomy-fact"><span>识别标志</span><b>${n.landmark}</b></div><div class="anatomy-fact"><span>操作提醒</span><b>${n.tip}</b></div>${im?`<div class="imgbox anatomy-img"><img src="${im.src}" onclick="openModal(this.src)" referrerpolicy="no-referrer" onerror="this.closest('.imgbox').classList.add('img-error')"></div><div class="src">${n.imgNote}<br>${im.credit} · <a href="${im.source}" target="_blank">真实图片来源/授权</a></div>`:''}<div class="row" style="margin-top:12px"><button class="btn ghost" ${anatomyIndex===0?'disabled':''} onclick="showAnatomyNode(${Math.max(0,anatomyIndex-1)})">← 上一站</button><button class="btn" onclick="showAnatomyNode(${Math.min(GI_ANATOMY[anatomyMode].nodes.length-1,anatomyIndex+1)})">下一站 →</button></div></div>`}
function startAnatomyQuiz(){anatomyQuizIndex=0;anatomyQuizScore=0;renderAnatomyQuiz()}
function renderAnatomyQuiz(){let qs=[...GI_ANATOMY_QUIZ],q=qs[anatomyQuizIndex],p=prof();$('#main').innerHTML=head('镜下部位识别闯关','每题只给关键内镜定位线索。先自己判断，再看解释。',`${anatomyQuizIndex+1}/${qs.length}`)+`<div class="quiz-shell"><div class="card quiz-scene"><div class="scope-screen"><div class="scope-reticle"></div><span>${q.tract==='upper'?'胃镜路线':'肠镜路线'}</span><h2>${q.q}</h2></div><div class="choices anatomy-choices">${q.o.map((o,i)=>`<div class="choice" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</div>`).join('')}</div><div id="aqexp"></div><button class="btn hidden" id="aqnext" style="margin-top:12px">${anatomyQuizIndex===qs.length-1?'查看成绩':'下一题 →'}</button></div></div>`;let locked=false;$$('.choice').forEach(el=>el.onclick=()=>{if(locked)return;locked=true;let i=+el.dataset.i,ok=i===q.a;if(window.moduleResponse24)moduleResponse24(q.q,q.o,i,ok,q.a,q.why);p.anatomy.total++;if(ok){p.anatomy.ok++;anatomyQuizScore++}save();$$('.choice').forEach(y=>{let j=+y.dataset.i;if(j===q.a)y.classList.add('correct');if(j===i&&!ok)y.classList.add('wrong')});$('#aqexp').className='feedback '+(ok?'good':'mid');$('#aqexp').innerHTML=`<b>${ok?'✓ 定位正确':'✗ 定位错误'}</b><br>${q.why}`;$('#aqnext').classList.remove('hidden');$('#aqnext').onclick=()=>{if(anatomyQuizIndex<qs.length-1){anatomyQuizIndex++;renderAnatomyQuiz()}else finishAnatomyQuiz()}})}
function finishAnatomyQuiz(){let p=prof(),pct=Math.round(anatomyQuizScore/GI_ANATOMY_QUIZ.length*100);if(window.finishModule24)finishModule24('recognition','解剖定位线索',pct);p.anatomy.best=Math.max(p.anatomy.best||0,pct);p.xp+=anatomyQuizScore*2;save();$('#main').innerHTML=head('镜下解剖闯关完成','能准确定位，才能谈病变描述和操作。','Anatomy Complete')+`<div class="grid g3">${metric('本轮成绩',pct+'%',`${anatomyQuizScore}/${GI_ANATOMY_QUIZ.length}`)}${metric('历史最好',p.anatomy.best+'%')}${metric('累计答题',p.anatomy.total,'题')}</div><div class="card" style="margin-top:16px"><h2>${pct>=80?'🎉 镜下定位基础扎实':'🧭 建议再走一遍镜子路线'}</h2><p>${pct>=80?'下一步可以把部位定位和病变识别、操作术式串起来。':'优先记住几个高价值地标：Z线、胃角、幽门、十二指肠大乳头、阑尾开口、回盲瓣。'}</p><div class="row"><button class="btn" onclick="startAnatomyQuiz()">再挑战一次</button><button class="btn soft" onclick="nav('anatomy')">返回解剖地图</button><button class="btn ghost" onclick="nav('procedures')">去学操作</button></div></div>`}

let currentProcedure=null, procStepOrder=[];
function procedures(){let p=prof();$('#main').innerHTML=head('内镜操作训练营','每个术式都不是“看一遍步骤”：先理解适应证，再做步骤排序、器械匹配和并发症决策。','Procedure Lab')+`<div class="procedure-banner"><div><span class="pill">Game-based Endoscopy</span><h2>从“知道术式名字”升级到“知道为什么做、先做什么、出问题怎么办”</h2><p>适用于规培/进修的认知训练，不替代模拟器和导师监督下的真实操作。</p></div><div class="proc-stats"><b>${Object.keys(p.procedures).length}</b><span>已训练术式</span></div></div><div class="procedure-grid">${GI_PROCEDURES.map(x=>{let st=p.procedures[x.id];return `<div class="proc-card ${x.color}" onclick="openProcedure('${x.id}')"><div class="proc-icon">${procIcon(x.id)}</div><div class="tags"><span class="tag hard">${x.level}</span><span class="tag">${x.badge}</span></div><h2>${x.name}</h2><p>${x.full}</p><div class="proc-progress">${st?`历史最好 <b>${st.best||0}%</b> · ${st.runs||0}轮`:'尚未训练'}</div><button class="btn soft">进入术式 →</button></div>`}).join('')}</div><div class="notice" style="margin-top:16px"><b>教学安全：</b>本模块训练术式认知、步骤和风险意识，不等于获得独立操作资质。ERCP/EUS/ESD/POEM等高级内镜需在规范培训、模拟训练和导师监督下逐步获得胜任力。</div>`}
function procIcon(id){return ({ESD:'✂️',EMR:'⭕',POEM:'🛤️',APC:'⚡',ERCP:'🟡','EUS-FNA':'🎯',ERAT:'🧩',EVL:'🪢',CLIP:'📎'}[id]||'🔧')}
function openProcedure(id){currentProcedure=GI_PROCEDURES.find(x=>x.id===id);renderProcedureOverview()}
function renderProcedureOverview(){let x=currentProcedure,im=GI_IMAGES[x.image],p=prof(),st=p.procedures[x.id]||{};$('#main').innerHTML=head(`${x.name} 操作训练`,x.full,`${x.level} · ${x.badge}`)+`<div class="procedure-layout"><div class="card"><div class="proc-title"><div class="proc-icon big">${procIcon(x.id)}</div><div><h2>${x.name}</h2><p>${x.full}</p></div></div>${im?`<div class="imgbox proc-image"><img src="${im.src}" onclick="openModal(this.src)" referrerpolicy="no-referrer"></div><div class="src">${x.imageNote}<br>${im.credit} · <a href="${im.source}" target="_blank">真实图片来源/授权</a></div>`:''}<div class="proc-info"><div><span>适应证/使用场景</span><p>${x.indications}</p></div><div><span>核心目标</span><p>${x.goal}</p></div><div><span>主要风险</span><p>${x.danger}</p></div></div></div><div class="card"><h2>训练关卡</h2><div class="level-list"><button onclick="startStepGame()"><b>01</b><span><strong>步骤排序</strong><small>把打乱的操作步骤按正确逻辑排回去</small></span></button><button onclick="startEquipmentGame()"><b>02</b><span><strong>器械匹配</strong><small>识别这台操作真正需要的器械</small></span></button><button onclick="startProcedureQuiz()"><b>03</b><span><strong>风险决策</strong><small>适应证、关键节点与并发症处理</small></span></button></div><h3>必须带走的要点</h3><ul class="pearl-list">${x.pearls.map(t=>`<li>${t}</li>`).join('')}</ul><div class="proc-score"><span>历史最好</span><b>${st.best||0}%</b><small>${st.runs||0} 次完整训练</small></div><button class="btn ghost" onclick="nav('procedures')">← 返回训练营</button></div></div>`}
function shuffled(a){return a.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function startStepGame(){let x=currentProcedure,items=shuffled(x.steps.map((s,i)=>({s,i})));procStepOrder=[];$('#main').innerHTML=head(`${x.name} · 步骤排序挑战`,'点击下方被打乱的步骤，依次构建你的操作流程。','Level 01')+`<div class="grid g2"><div class="card"><h2>步骤池</h2><p class="muted">点击一个步骤，它会进入右侧“你的流程”。</p><div id="stepPool" class="step-pool">${items.map(o=>`<button class="step-chip" data-i="${o.i}">${o.s}</button>`).join('')}</div></div><div class="card"><h2>你的流程</h2><div id="stepAnswer" class="step-answer"><div class="empty">还没有选择步骤</div></div><div class="row"><button class="btn" id="checkSteps">提交排序</button><button class="btn ghost" onclick="startStepGame()">重新打乱</button></div><div id="stepFeedback"></div></div></div>`;$$('.step-chip').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;procStepOrder.push(+b.dataset.i);renderStepAnswer()});$('#checkSteps').onclick=checkStepOrder}
function renderStepAnswer(){let x=currentProcedure;$('#stepAnswer').innerHTML=procStepOrder.length?procStepOrder.map((i,n)=>`<div class="answer-step"><b>${n+1}</b><span>${x.steps[i]}</span></div>`).join(''):'<div class="empty">还没有选择步骤</div>'}
function checkStepOrder(){let x=currentProcedure;if(procStepOrder.length!==x.steps.length)return alert('请先把所有步骤都排入流程');let correct=procStepOrder.filter((v,i)=>v===i).length,pct=Math.round(correct/x.steps.length*100),f=$('#stepFeedback');f.className='feedback '+(pct===100?'good':'mid');f.innerHTML=`<b>${pct===100?'✓ 顺序完全正确':'本轮顺序吻合度 '+pct+'%'}</b><br>${pct===100?'很好。下一关开始考器械和风险。':'标准流程：<ol>'+x.steps.map(s=>`<li>${s}</li>`).join('')+'</ol>'}<div class="row" style="margin-top:10px"><button class="btn" onclick="startEquipmentGame()">下一关：器械匹配 →</button><button class="btn ghost" onclick="renderProcedureOverview()">返回术式主页</button></div>`}
function startEquipmentGame(){let x=currentProcedure,decoys=['活检钳','鼻胆管','食管扩张探条','PEG套件','止血喷粉','胶囊内镜','取异物网篮','球囊扩张导管'].filter(d=>!x.equipment.includes(d));let opts=shuffled([...x.equipment.slice(0,Math.min(5,x.equipment.length)),...decoys.slice(0,3)]);$('#main').innerHTML=head(`${x.name} · 器械匹配`,'把你认为属于本术式核心器械的项目全部选出来。','Level 02')+`<div class="card"><div class="equipment-grid">${opts.map((o,i)=>`<button class="equip" data-v="${esc(o)}"><span>🔧</span>${o}</button>`).join('')}</div><button class="btn" id="equipCheck">提交器械选择</button><div id="equipFeedback"></div></div>`;$$('.equip').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));$('#equipCheck').onclick=()=>{let sel=$$('.equip.selected').map(b=>b.dataset.v),core=x.equipment.slice(0,Math.min(5,x.equipment.length)),hit=core.filter(e=>sel.includes(e)).length,wrong=sel.filter(e=>!x.equipment.includes(e)).length,pct=Math.max(0,Math.round((hit/core.length-wrong/Math.max(1,opts.length))*100)),f=$('#equipFeedback');f.className='feedback '+(pct>=80?'good':'mid');f.innerHTML=`<b>器械匹配 ${pct}%</b><br>核心器械包括：${x.equipment.join('、')}。<div class="row" style="margin-top:10px"><button class="btn" onclick="startProcedureQuiz()">下一关：风险决策 →</button><button class="btn ghost" onclick="renderProcedureOverview()">返回术式主页</button></div>`}}
let procQuizIndex=0,procQuizCorrect=0;
function startProcedureQuiz(){procQuizIndex=0;procQuizCorrect=0;renderProcedureQuiz()}
function renderProcedureQuiz(){let x=currentProcedure,q=x.quiz[procQuizIndex];$('#main').innerHTML=head(`${x.name} · 风险决策`,'不要只背步骤：判断什么时候做、哪里最危险、出了问题先想什么。',`Level 03 · ${procQuizIndex+1}/${x.quiz.length}`)+`<div class="quiz-shell"><div class="card"><div class="clinical-prompt"><span>${x.name}</span><h2>${q.q}</h2></div><div class="choices">${q.o.map((o,i)=>`<div class="choice" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</div>`).join('')}</div><div id="pqexp"></div><button id="pqnext" class="btn hidden" style="margin-top:12px">${procQuizIndex===x.quiz.length-1?'完成本术式训练':'下一题 →'}</button></div></div>`;let locked=false;$$('.choice').forEach(el=>el.onclick=()=>{if(locked)return;locked=true;let i=+el.dataset.i,ok=i===q.a;if(window.moduleResponse24)moduleResponse24(q.q,q.o,i,ok,q.a,q.why);if(ok)procQuizCorrect++;$$('.choice').forEach(y=>{let j=+y.dataset.i;if(j===q.a)y.classList.add('correct');if(j===i&&!ok)y.classList.add('wrong')});$('#pqexp').className='feedback '+(ok?'good':'mid');$('#pqexp').innerHTML=`<b>${ok?'✓ 正确':'✗ 需要再想一步'}</b><br>${q.why}`;$('#pqnext').classList.remove('hidden');$('#pqnext').onclick=()=>{if(procQuizIndex<x.quiz.length-1){procQuizIndex++;renderProcedureQuiz()}else finishProcedureTraining()}})}
function finishProcedureTraining(){if(window.finishModule24)finishModule24('procedure',currentProcedure.name,Math.round(procQuizCorrect/currentProcedure.quiz.length*100));let x=currentProcedure,p=prof(),pct=Math.round(procQuizCorrect/x.quiz.length*100),st=p.procedures[x.id]||{best:0,runs:0};st.best=Math.max(st.best||0,pct);st.runs=(st.runs||0)+1;st.last=new Date().toISOString();p.procedures[x.id]=st;p.xp+=10+procQuizCorrect*3;save();$('#main').innerHTML=head(`${x.name} 训练完成`,'把认知流程练熟，再进入模拟器和导师监督下的真实操作。','Procedure Complete')+`<div class="grid g3">${metric('风险决策',pct+'%',`${procQuizCorrect}/${x.quiz.length}`)}${metric('历史最好',st.best+'%')}${metric('完成轮次',st.runs,'次')}</div><div class="card" style="margin-top:16px"><h2>操作记忆卡</h2><div class="memory-flow">${x.steps.map((s,i)=>`<div><b>${i+1}</b><span>${s}</span></div>`).join('')}</div><h3>风险提醒</h3><p>${x.danger}</p><div class="row"><button class="btn" onclick="openProcedure('${x.id}')">再练一次</button><button class="btn soft" onclick="nav('procedures')">换一个术式</button><button class="btn ghost" onclick="nav('anatomy')">回到解剖地图</button></div></div>`}
window.switchAnatomy=switchAnatomy;window.showAnatomyNode=showAnatomyNode;window.startAnatomyQuiz=startAnatomyQuiz;window.openProcedure=openProcedure;window.startStepGame=startStepGame;window.startEquipmentGame=startEquipmentGame;window.startProcedureQuiz=startProcedureQuiz;window.renderProcedureOverview=renderProcedureOverview;
window.openModal=openModal;window.closeModal=closeModal;window.nav=nav;window.startCase=startCase;window.renderWard=renderWard;window.removeWrong=removeWrong;window.exportData=exportData;window.resetAll=resetAll;window.delCustom=delCustom;
document.body.innerHTML='<p role="status">正在加载住培教学平台…</p>';

