(function(){
const P='assets/procedure/tools/official_hd/';
const TOOLS={
 '注射针':{main:P+'injection_interject.jpg',detail:P+'injection_tip.jpg',model:'Interject™ Injection Therapy Needle Catheter',use:'黏膜下注射、止血注射、EMR/ESD 病灶抬举',clue:'细节图可见针鞘与斜面针尖。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/needles/interject-sclerotherapy-needles.html'},
 'DualKnife':{main:P+'dualknife_full.jpg',model:'Olympus DualKnife J · KD-655',use:'ESD 切开、标记、剥离及送液',clue:'短针状刀头末端有小圆盘；与三角头隧道刀不同。',source:'Olympus',url:'https://www.olympus-medical.jp/product/esd/dualknife_j'},
 'Coagrasper':{main:P+'coagrasper_full.png',detail:P+'coagrasper_feature.jpeg',model:'Olympus Coagrasper · FD-410LR/FD-412LR',use:'夹持出血血管并进行目标性电凝止血',clue:'放大图可见宽钳口、止滑齿及对合面。',source:'Olympus',url:'https://www.olympus-medical.jp/product/hemo/coagrasper'},
 '圈套器':{main:P+'snare_photo.jpg',model:'Captivator™ II Single-Use Snare',use:'EMR、冷热圈套息肉切除',clue:'可见圆形圈套钢丝、连接部及蓝色外鞘。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/snares/captivator-II-single-use-snare.html'},
 'APC探头':{main:'assets/procedure/tools/APC探头_display.png',model:'APC probe',use:'氩离子凝固与浅表止血',clue:'沿用原有清晰本地实物图。',source:'项目原有素材',url:''},
 '止血夹':{main:'assets/procedure/tools/止血夹_display.png',model:'Endoscopic clip',use:'创面闭合与机械止血',clue:'沿用原有清晰本地实物图。',source:'项目原有素材',url:''},
 '套扎器':{main:P+'ligator.jpg',detail:P+'ligator_detail.jpg',model:'Speedband Superview Super 7™',use:'食管静脉曲张及痔的内镜套扎',clue:'细节图可见透明套扎帽、后置蓝色皮圈和释放线。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/band-ligator/speedband-superview-super-7.html'},
 'FNA穿刺针':{main:P+'fna_expect.jpg',detail:P+'fna_tip.jpg',model:'Expect™ Slimline EUS-FNA Needle',use:'EUS 引导细针穿刺抽吸，主要获取细胞学标本',clue:'本页所示型号为蓝色手柄；针尖为斜面单刃结构，近针尖有环形回声纹。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/needles/endoscopic-ultrasound-fine-needle-aspiration.html'},
 'FNB穿刺针':{main:P+'fnb_acquire.jpg',detail:P+'fnb_tip.jpg',model:'Acquire™ EUS-FNB Device',use:'EUS 引导细针活检，主要获取组织条/组织学标本',clue:'本页所示型号为绿色手柄；Franseen 三叉冠状针尖具有三个切割刃。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/needles/acquire-endoscopic-ultrasound-fine-needle.html'},
 '乳头切开刀':{main:P+'sphincterotome_full.jpg',detail:P+'sphincterotome_detail1.jpg',model:'Olympus CleverCut 3 V',use:'ERCP 选择性插管及十二指肠乳头切开',clue:'高分辨率全图可见预弯导管、切割钢丝和彩色标记；细节图显示手柄。',source:'Olympus',url:'https://www.olympus-medical.jp/product/ercp_papilla/clevercut3v'},
 '导丝':{main:'assets/procedure/tools/导丝_display.png',model:'ERCP guidewire',use:'ERCP/ERAT 建立和保持通道',clue:'沿用原有清晰本地实物图。',source:'项目原有素材',url:''},
 '取石球囊':{main:P+'stone_balloon.jpg',model:'Extractor™ Pro Retrieval Balloon Catheter',use:'ERCP 胆管结石回拉取出及造影',clue:'可见三种充盈直径、方肩球囊、导丝和手柄。',source:'Boston Scientific',url:'https://www.bostonscientific.com/en-US/products/Balloons-Dilation-Extraction/extractor-pro-rx-retrieval_balloons.html'},
 '隧道刀':{main:P+'tunnel_full.jpeg',detail:P+'tunnel_knife.jpg',model:'Olympus TriangleTipKnife J · KD-645L',use:'POEM 黏膜下隧道建立、切开与凝固',clue:'刀头末端为三角形，不是 DualKnife 的小圆盘针状头。',source:'Olympus',url:'https://www.olympus-medical.jp/product/esd/triangle_tip_knife_j'},
 '冲洗导管':{main:P+'irrigation_catheter.jpg',model:'Cook Medical Glo-Tip® II Double Lumen ERCP Catheter',use:'导管形态识别；液体注入/造影的双腔导管示例',clue:'放大图可见透明圆钝头端、黑色显影标记及双腔结构。ERAT 冲洗应以科室实际导管为准。',source:'Cook Medical',url:'https://www.cookmedical.com/products/esc_gtii_webds/'},
 '切开刀':{main:P+'dualknife_full.jpg',model:'Olympus DualKnife J',use:'内镜切开与剥离',clue:'使用 DualKnife J 官方实物图。',source:'Olympus',url:'https://www.olympus-medical.jp/product/esd/dualknife_j'}
};
const ORDER=['注射针','DualKnife','Coagrasper','圈套器','APC探头','止血夹','套扎器','乳头切开刀','导丝','取石球囊','FNA穿刺针','FNB穿刺针','隧道刀','冲洗导管'];
const M=Object.fromEntries(Object.entries(TOOLS).map(([name,item])=>[name,item.main]));
function nameFrom(el){if(!el||el.dataset.v23Recovered)return null;const name=el.getAttribute('alt');if(name&&M[name])return name;const box=el.closest('.v7-tool,.v12tool,.v13tool,.v14-tool,.v15tool,.v16tool,.rp-tool,.toollab-card');return box?.dataset.tool&&M[box.dataset.tool]?box.dataset.tool:null;}
function patch(root=document){ root.querySelectorAll('img').forEach(img=>{ if(img.closest('.v19card, .v19lightbox')) return; const n=nameFrom(img); if(!n) return; const want=M[n]; if(img.getAttribute('src')!==want) img.src=want; img.alt=n; img.onerror=function(){this.onerror=null;this.src=want;}; img.loading='eager'; img.dataset.toolImage='true'; }); }
function photo(src,name){return `<button class="v19photo" type="button" onclick="openToolImage('${src}','${name}')" aria-label="放大查看${name}"><img src="${src}" alt="${name}"><span>${name}</span></button>`;}
function card(name){const item=TOOLS[name];const source=item.url?`<a href="${item.url}" target="_blank" rel="noopener">官方来源：${item.source}</a>`:`<span>来源：${item.source}</span>`;return `<article class="v19card" data-tool="${name}"><div class="v19gallery ${item.detail?'two':''}">${photo(item.main,name)}${item.detail?photo(item.detail,name):''}</div><div class="v19copy"><h3>${name}</h3><strong>${item.model}</strong><p>${item.use}</p><div class="v19clue">识别要点：${item.clue}</div><small>${source}</small></div></article>`;}
window.fixAllToolImages=patch;
window.openToolImage=function(src,alt){let box=document.getElementById('v19lightbox');if(!box){box=document.createElement('div');box.id='v19lightbox';box.className='v19lightbox';box.innerHTML='<button type="button" aria-label="关闭">×</button><img><p></p>';box.addEventListener('click',e=>{if(e.target===box||e.target.tagName==='BUTTON')box.classList.remove('show')});document.body.appendChild(box);}box.querySelector('img').src=src;box.querySelector('img').alt=alt;box.querySelector('p').textContent=alt;box.classList.add('show');};
window.openToolAtlas=function(){ $('#main').innerHTML=head('高清真实器械图库','使用厂商官方产品照片；点击任意图片可查看原始大图和关键结构。','OFFICIAL HD TOOL ATLAS')+`<div class="notice"><b>本版重点：</b>已替换注射针、DualKnife、Coagrasper、圈套器、套扎器、乳头切开刀、取石球囊、隧道刀和导管图。本页 FNA 与 FNB 器械型号图分别展示（教程的共享穿刺图另有标注）。</div><section class="v19compare"><h2>FNA 与 FNB 快速区分</h2><div><p><b>FNA：</b>本页所示型号为蓝色手柄、斜面单刃针尖，侧重抽吸细胞学标本。</p><p><b>FNB：</b>本页所示型号为绿色手柄、Franseen 三叉冠状针尖，侧重获取组织条。</p></div></section><div class="v19atlas">${ORDER.map(card).join('')}</div><div class="notice v19copyright"><b>图片说明：</b>器械照片来自所列厂商官方产品页，仅用于本地教学识别；商标与图片版权归各权利人。临床使用请查阅产品说明书和本机构规范。</div><div class="row" style="margin-top:16px"><button class="btn ghost" onclick="procedures()">返回术式页</button></div>`; patch(document); };
const oldProc=window.procedures; if(oldProc){ window.procedures=function(){ oldProc(); const grid=document.querySelector('.procedure-grid'); if(grid){ const note=document.createElement('div'); note.className='notice'; note.style.margin='12px 0 16px'; note.innerHTML='<b>高清器械图：</b>训练页已统一使用官方实物照片；完整细节和 FNA/FNB 对比请打开“器械图库”。'; grid.before(note);} patch(document); }; }
window.addEventListener('load',()=>{ patch(document); setTimeout(()=>patch(document),300); setTimeout(()=>patch(document),1500); });
window.addEventListener('click',()=>setTimeout(()=>patch(document),80),true);
const mo=new MutationObserver(()=>patch(document)); mo.observe(document.documentElement,{subtree:true,childList:true});
const st=document.createElement('style'); st.textContent=`.v19atlas{display:grid;grid-template-columns:1fr;gap:18px}.v19card{display:grid;grid-template-columns:minmax(340px,46%) 1fr;gap:20px;background:#fff;border:1px solid #dfe6ee;border-radius:20px;padding:16px;align-items:center;box-shadow:0 5px 18px rgba(16,24,40,.05)}.v19gallery{display:grid;grid-template-columns:1fr;gap:10px}.v19gallery.two{grid-template-columns:1fr 1fr}.v19photo{position:relative;padding:0;border:1px solid #e4e7ec;border-radius:14px;overflow:hidden;background:#f8fafc;cursor:zoom-in}.v19photo img{width:100%;height:230px;object-fit:contain;display:block;background:#fff}.v19photo span{position:absolute;right:8px;bottom:8px;background:#101828d9;color:#fff;border-radius:999px;padding:4px 8px;font-size:11px}.v19copy h3{margin:0 0 4px;font-size:22px}.v19copy strong{display:block;color:#175cd3;margin-bottom:10px}.v19copy p{margin:0 0 10px;color:#475467}.v19clue{background:#eff8ff;color:#1849a9;border-radius:10px;padding:9px 11px;line-height:1.55}.v19copy small{display:block;margin-top:10px;color:#667085}.v19copy a{color:#175cd3}.v19compare{margin:0 0 18px;background:linear-gradient(135deg,#eff8ff,#ecfdf3);border:1px solid #b2ddff;border-radius:18px;padding:16px}.v19compare h2{margin:0 0 10px}.v19compare>div{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v19compare p{margin:0;background:#fff;border-radius:12px;padding:12px}.v19copyright{margin-top:18px}.v19lightbox{display:none;position:fixed;z-index:99999;inset:0;background:rgba(0,0,0,.88);align-items:center;justify-content:center;flex-direction:column;padding:28px}.v19lightbox.show{display:flex}.v19lightbox img{max-width:94vw;max-height:82vh;object-fit:contain;background:#fff;border-radius:12px}.v19lightbox p{color:#fff;font-weight:700}.v19lightbox button{position:absolute;right:24px;top:18px;border:0;background:#fff;color:#101828;width:44px;height:44px;border-radius:999px;font-size:30px;cursor:pointer}.v7-tool img,.v12tool img,.v13tool img,.v14-tool img,.v15tool img,.v16tool img,.rp-tool img,.toollab-card img,.v13atlas-card img,.v15card img,.v16card img,.v17card img{background:#fff;min-height:70px;object-fit:contain}@media(max-width:900px){.v19card{grid-template-columns:1fr}.v19photo img{height:200px}.v19compare>div{grid-template-columns:1fr}}@media(max-width:520px){.v19gallery.two{grid-template-columns:1fr}.v19photo img{height:240px}}`; document.head.appendChild(st);
})();
