(function(){
const A='assets/procedure/';
const toolImg={
 '注射针':'assets/procedure/tools/注射针_display.png','DualKnife':'assets/procedure/tools/DualKnife_display.png','Coagrasper':'assets/procedure/tools/Coagrasper_display.png','圈套器':'assets/procedure/tools/圈套器_display.png','APC探头':'assets/procedure/tools/APC探头_display.png','导丝':'assets/procedure/tools/导丝_display.png','取石球囊':'assets/procedure/tools/取石球囊_display.png','FNB穿刺针':'assets/procedure/tools/FNB穿刺针_display.png','止血夹':'assets/procedure/tools/止血夹_display.png','隧道刀':'assets/procedure/tools/隧道刀_display.png'};
const sims={
 ESD:{title:'ESD · 胃早癌整块切除',case:'63岁男性，胃体小弯0-IIa型早期胃癌，约18 mm，拟行ESD。',bg:A+'lesions/esd_early_gastric_cancer_close.jpg',fit:'contain',source:'真实病灶：Early stomach cancer 2a，Wikimedia Commons，CC BY-SA 3.0',link:'https://commons.wikimedia.org/wiki/File:Early_stomach_cancer_2a.jpg',tools:['注射针','DualKnife','Coagrasper','止血夹'],steps:[
  {name:'黏膜下注射抬举',tool:'注射针',hint:'把注射针拖到病灶基底周围的蓝色目标区。',spots:[[61,58,9,8],[71,62,9,8],[66,73,10,8]],effect:'lift'},
  {name:'沿病灶外缘切开',tool:'DualKnife',hint:'把DualKnife依次拖到病灶边界的切开点。',spots:[[57,62,7,7],[67,55,7,7],[76,63,7,7],[68,76,7,7],[58,72,7,7]],effect:'cut'},
  {name:'处理显露血管',tool:'Coagrasper',hint:'剥离床出现可见血管，把Coagrasper拖到红色血管区。',spots:[[68,67,8,8]],effect:'coag'}]},
 EMR:{title:'EMR · 乙状结肠腺瘤切除',case:'59岁男性，乙状结肠6–7 mm管状腺瘤，低级别上皮内瘤变，拟行EMR。',bg:A+'lesions/emr_sigmoid_adenoma.jpg',fit:'cover',source:'真实病灶：Sigmoid tubular adenoma，Wikimedia Commons，CC BY-SA 3.0',link:'https://commons.wikimedia.org/wiki/File:Polyp_(tubular_adenoma)_in_sigmoid_colon.jpg',tools:['注射针','圈套器','止血夹'],steps:[
  {name:'病灶基底注射',tool:'注射针',hint:'把注射针拖到息肉基底，形成抬举。',spots:[[54,61,14,13]],effect:'lift'},
  {name:'圈套器捕获病灶',tool:'圈套器',hint:'把圈套器拖到整个息肉头部，使圈套器包绕病灶。',spots:[[53,50,23,26]],effect:'snare'},
  {name:'切除后创面评估/夹闭',tool:'止血夹',hint:'模拟切除后出现小血管，拖动止血夹到创面中心。',spots:[[54,60,11,10]],effect:'clip'}]},
 APC:{title:'APC · GAVE靶向凝固',case:'慢性贫血患者，胃窦见典型“西瓜胃”放射状血管扩张，拟行APC。',bg:A+'lesions/apc_gave_before.png',fit:'contain',source:'真实病灶：GAVE before/after APC，Wikimedia Commons / Public Domain',link:'https://commons.wikimedia.org/wiki/File:Gastric_antral_vascular_ectasia_(before_and_after).png',tools:['APC探头','止血夹'],steps:[
  {name:'分区、点状APC',tool:'APC探头',hint:'依次处理放射状血管条带；不要在同一点长时间停留。',spots:[[42,37,9,7],[50,46,9,7],[57,55,9,7],[45,58,9,7],[61,69,9,7]],effect:'coag'}]},
 ERCP:{title:'ERCP · 胆总管结石取石',case:'胆管炎患者，造影见远端胆总管嵌顿结石。完成导丝通过并选择合适取石器械。',bg:A+'lesions/ercp_stone.jpg',fit:'contain',source:'真实影像：ERCP distal CBD stone，Wikimedia Commons / Public Domain',link:'https://commons.wikimedia.org/wiki/File:ERCP_stone.jpg',tools:['导丝','取石球囊'],steps:[
  {name:'导丝越过结石进入近端胆管',tool:'导丝',hint:'把导丝拖到结石以上的胆管腔。',spots:[[47,27,12,10]],effect:'wire'},
  {name:'球囊拖石',tool:'取石球囊',hint:'把取石球囊拖到结石近端，模拟充盈后向乳头方向拖出。',spots:[[42,37,12,12]],effect:'balloon'}]},
 'EUS-FNA':{title:'EUS-FNB · 胰腺实性占位取材',case:'72岁男性梗阻性黄疸，EUS见胰头实性低回声占位。避开Doppler血管后获取组织。',bg:'',fit:'cover',source:'本关病灶背景为教学模拟EUS画面；器械与动作训练用于认知教学。',tools:['FNB穿刺针'],simulated:'eus',steps:[{name:'无血管路径穿刺靶病灶',tool:'FNB穿刺针',hint:'拖针尖进入黄色低回声占位，避开红色Doppler血管。',spots:[[70,51,16,18]],effect:'needle'}]},
 POEM:{title:'POEM · 贲门失弛缓症隧道内肌切开',case:'35岁女性，Eckardt 8分，II型贲门失弛缓症。建立黏膜下隧道并完成跨EGJ肌切开。',bg:'assets/anatomy/zline.jpg',fit:'cover',source:'解剖背景为EGJ真实内镜图；本关的隧道范围为教学叠加。',tools:['注射针','隧道刀','止血夹'],steps:[{name:'入口下注射',tool:'注射针',hint:'在拟入口区域下注射形成黏膜下垫。',spots:[[46,38,11,9]],effect:'lift'},{name:'隧道方向切开',tool:'隧道刀',hint:'沿纵向隧道靶区推进到EGJ远端。',spots:[[48,47,10,8],[52,58,10,8],[55,69,10,8]],effect:'cut'}]},
 ERAT:{title:'ERAT · 阑尾腔减压与引流',case:'单纯性急性阑尾炎，内镜到达盲肠后识别阑尾开口并尝试导丝进入阑尾腔。',bg:'assets/anatomy/appendiceal_orifice.jpg',fit:'cover',source:'背景为真实阑尾开口内镜图片；导丝路径为教学模拟。',tools:['导丝'],steps:[{name:'导丝进入阑尾开口',tool:'导丝',hint:'把导丝拖到阑尾开口中央，而不是盲目顶压周围黏膜。',spots:[[50,49,16,16]],effect:'wire'}]}
};
let S=null,selected='';
function tile(t){return `<div class="v6-tool" draggable="true" data-tool="${t}" onclick="v6SelectTool('${t}')"><img src="${toolImg[t]}" alt="${t}"><div class="tname">${t}</div></div>`}
window.procedures=function(){
  const cards=Object.keys(sims).map(id=>{let s=sims[id];return `<div class="v6-casecard" onclick="launchArcade('${id}')">${s.bg?`<img src="${s.bg}">`:`<div style="height:150px;background:radial-gradient(circle at 68% 50%,#5f5f5f 0 13%,#1b1b1b 14% 55%,#050505 56%);display:grid;place-items:center;color:white;font-weight:900">EUS SIM</div>`}<div class="body"><h3>${s.title}</h3><p>${s.case}</p><span class="tag">拖拽操作游戏</span></div></div>`}).join('');
  $('#main').innerHTML=head('Endoscopy Procedure Lab v6','具体病变 + 器械图片 + 拖拽到指定区域。先看病灶，再动器械。','DRAG & DROP')+`<div class="v6-thumbgrid">${cards}</div><div class="notice" style="margin-top:18px"><b>器械图片说明：</b>圈套器使用开放授权真实器械照片；其他器械目前为清晰教学图卡，避免直接使用厂商受版权保护的商品图。后续可替换为医院/厂商授权的真实器械照片。</div>`;
};
window.launchArcade=function(id){if(!sims[id])return;S={id,step:0,spot:0,score:0,lives:3,start:Date.now(),expert:false};selected='';renderSim()};
window.v6SelectTool=function(t){selected=t;document.querySelectorAll('.v6-tool').forEach(x=>x.classList.toggle('active',x.dataset.tool===t));let m=document.querySelector('.v6-msg');if(m)m.textContent='已选择 '+t+'；也可以直接拖拽器械图片到目标区。'};
function renderSim(){let d=sims[S.id],st=d.steps[S.step];$('#main').innerHTML=head(d.title,d.case,'OPERATOR MODE')+`<div class="v6-lab"><div class="v6-casebar"><div><h3>当前任务：${st.name}</h3><p>${st.hint}</p><div class="v6-source">${d.source}${d.link?` · <a href="${d.link}" target="_blank">查看原始来源</a>`:''}</div></div><div class="v6-mode"><button class="${S.expert?'':'active'}" onclick="v6Mode(false)">教学模式</button><button class="${S.expert?'active':''}" onclick="v6Mode(true)">专家模式</button></div></div><div class="v6-stage"><div class="v6-monitor" id="v6monitor">${d.bg?`<img class="v6-bg ${d.fit==='cover'?'cover':''}" src="${d.bg}">`:`<div class="v6-bg" style="background:radial-gradient(circle at 70% 51%,#6f6f6f 0 12%,#3c3c3c 13% 18%,#151515 19% 60%,#050505 61%)"></div>`}<div class="v6-label">${d.title}</div><div class="v6-hud" id="v6hud">SCORE ${S.score} · LIFE ${'♥'.repeat(S.lives)}${'♡'.repeat(3-S.lives)}</div><div class="v6-overlay" id="v6overlay"></div><div class="v6-msg">${st.hint}</div></div><aside class="v6-tray"><h3>器械托盘</h3><small>拖住图片 → 放到画面目标区域</small>${d.tools.map(tile).join('')}<div class="v6-stepbox">${d.steps.map((x,i)=>`<div class="v6-step ${i<S.step?'done':i===S.step?'current':''}"><b>${i<S.step?'✓':i+1}</b><span>${x.name}</span></div>`).join('')}</div></aside></div></div>`;bindDnD();drawSpots();}
window.v6Mode=function(x){S.expert=x;renderSim()};
function bindDnD(){document.querySelectorAll('.v6-tool').forEach(el=>{el.addEventListener('dragstart',e=>{selected=el.dataset.tool;e.dataTransfer.setData('text/plain',selected);setTimeout(()=>el.classList.add('active'),0)});el.addEventListener('dragend',()=>{})});let o=$('#v6overlay');o.addEventListener('dragover',e=>e.preventDefault());o.addEventListener('drop',e=>{e.preventDefault();let t=e.dataTransfer.getData('text/plain')||selected, r=o.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;attempt(t,x,y)});o.addEventListener('click',e=>{if(!selected)return;let r=o.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;attempt(selected,x,y)})}
function drawSpots(){let st=sims[S.id].steps[S.step],o=$('#v6overlay');st.spots.forEach((p,i)=>{let h=document.createElement('div');h.className='v6-hotspot '+(S.expert?'hiddenhint':'');h.style.left=(p[0]-p[2]/2)+'%';h.style.top=(p[1]-p[3]/2)+'%';h.style.width=p[2]+'%';h.style.height=p[3]+'%';h.dataset.i=i;o.appendChild(h)});if(sims[S.id].simulated==='eus'){let v=document.createElement('div');v.style.cssText='position:absolute;left:48%;top:25%;width:9%;height:38%;border-radius:999px;background:#d92d20aa;box-shadow:0 0 18px #f04438';o.appendChild(v)}}
function attempt(tool,x,y){let d=sims[S.id],st=d.steps[S.step],p=st.spots[S.spot];if(tool!==st.tool)return penalize('器械不匹配：当前步骤需要 '+st.tool);if(d.simulated==='eus'&&x>46&&x<60&&y>22&&y<66)return penalize('碰到Doppler血管，请重新选择穿刺路径');let dx=(x-p[0])/(p[2]||10),dy=(y-p[1])/(p[3]||10);if(Math.sqrt(dx*dx+dy*dy)>1.2)return penalize('器械没有落在正确的病灶/靶区域');S.score+=100;markEffect(p,st.effect);let hs=document.querySelectorAll('.v6-hotspot');if(hs[S.spot])hs[S.spot].classList.add('done');S.spot++;updateHud('✓ '+st.name+'：第 '+S.spot+'/'+st.spots.length+' 个靶点完成');if(S.spot>=st.spots.length){S.step++;S.spot=0;if(S.step>=d.steps.length)return setTimeout(finish,700);setTimeout(renderSim,650)}}
function markEffect(p,e){let o=$('#v6overlay'),z=document.createElement('div');z.className='v6-effect '+(e==='lift'?'v6-lift':e==='coag'?'v6-coag':'v6-cut');z.style.left=(p[0]-p[2]/2)+'%';z.style.top=(p[1]-p[3]/2)+'%';z.style.width=p[2]+'%';z.style.height=p[3]+'%';if(e==='cut'){z.style.transform='rotate('+(Math.random()*90-45)+'deg)'}o.appendChild(z)}
function penalize(m){S.lives--;S.score=Math.max(0,S.score-25);updateHud('⚠ '+m);if(S.lives<=0)setTimeout(finish,550)}
function updateHud(msg){let h=$('#v6hud'),m=document.querySelector('.v6-msg');if(h)h.textContent=`SCORE ${S.score} · LIFE ${'♥'.repeat(Math.max(0,S.lives))}${'♡'.repeat(3-Math.max(0,S.lives))}`;if(m)m.textContent=msg}
function finish(){let o=$('#v6overlay'),sec=Math.max(1,Math.round((Date.now()-S.start)/1000)),win=S.lives>0&&S.step>=sims[S.id].steps.length,bonus=win?Math.max(0,250-sec):0,total=S.score+bonus,stars=win?(total>=500?3:total>=300?2:1):0;o.innerHTML+=`<div class="v6-finish"><div><h2>${win?'MISSION COMPLETE':'MISSION FAILED'}</h2><div class="score">${total}</div><div style="font-size:34px;margin:4px 0 14px">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>用时 ${sec}s · 剩余生命 ${Math.max(0,S.lives)}/3</p><button class="btn" onclick="launchArcade('${S.id}')">再练一轮</button> <button class="btn soft" onclick="procedures()">返回操作训练营</button></div></div>`}
try{document.title='GI Resident AI V24.0 · 住培辅助教学';document.querySelectorAll('.logo small').forEach(x=>x.textContent='RESIDENCY TRAINING · V6');document.querySelectorAll('.login .pill').forEach(x=>x.textContent='GI Resident AI · v6')}catch(e){}
})();
